### ISSUE TITLE
Unable to use plugin on MusicBrainz Picard

### ISSUE THREAD

**Issue by bolleyboll** [avalloneandrea/apiseeds-lyrics#1]
I'm unable to add the API key from APIseeds to the Picard.

The documentation for Picard indicated that upon installing a plugin I should be able to find some sort of options to interact with the settings of an API(including adding API keys). This, however, wasn't possible with your plugin.

Any help as to how to use the plugin on Picard would be helpful. @avalloneandrea

**Comment by avalloneandrea** [comment]
In order to set your API key you should (a) open the _Preferences_ pane, (b) expand the _Plugins_ item by clicking the arrow you can see before the text, and finally (c) select the _Apiseeds Lyrics_ item.
![Screenshot](https://user-images.githubusercontent.com/9071642/71240558-bbc2b900-2309-11ea-83dc-fc7b89be01a5.png)

**Comment by bolleyboll** [comment]
![image](https://user-images.githubusercontent.com/31176934/71341640-74922d80-2580-11ea-8edb-bb3dd91862e5.png)

Windows user here, after installation the plugin gets automatically deactivated.
Reactivating the plugin does nothing and there is no sign of the drop-down arrow even when I reactivate the plugin.

**Comment by avalloneandrea** [comment]
I've just made a fresh install of Picard on a PC with Windows, and I've installed the plugin flawlessly. Have you tried uninstalling and reinstalling Picard? If it doesn't work, then (a) uninstall the plugin, (b) open the log (Help > Show error/debug log), (c) set the verbosity to debug, (d) reinstall the plugin, and (e) share what the log says.
