### ISSUE TITLE
apiseeds is being replaced by happi.dev

### ISSUE THREAD

**Issue by mtfurlan** [avalloneandrea/apiseeds-lyrics#3]
https://apiseeds.com is no longer allowing new registrations, and is redirecting people to https://happi.dev
Is there a plan to update this plugin to work with that?

Looking into the new API I don't understand their design at all.
https://happi.dev/docs/music
The lyric api requires their artist/album/track IDs and you can't just search by text like you can in the apiseed API.
The only way I see to do it is call the search endpoint for the artist, get the artist id, call the albums endpoint with the artist, manually find the album in the result, then call the tracks endpoint, manually find the track, and *then* call the lyrics API.

Their contact form is broken, so I can't even ask them what I'm missing here.

Throwaway api key for anyone to play with: `749bc35xp2wI2uOhyuwQ51FbIVwKN2w3Oow64MPIsNNmOnZYIwQXhVwr`

**Comment by ruslaniv** [comment]
Yes, I would like to see this updated as well ti work with the new API provider.

**Comment by Robertschv** [comment]
Yes, apparently this will not work anymore till its change to happi.dev

**Comment by Robertschv** [comment]
There is a Happi.dev complement for Picard
[https://github.com/metabrainz/picard-plugins/pull/293](url)

**Comment by jodacame** [comment]
> https://apiseeds.com is no longer allowing new registrations, and is redirecting people to https://happi.dev
> 
> Is there a plan to update this plugin to work with that?
> 
> 
> 
> Looking into the new API I don't understand their design at all.
> 
> https://happi.dev/docs/music
> 
> The lyric api requires their artist/album/track IDs and you can't just search by text like you can in the apiseed API.
> 
> The only way I see to do it is call the search endpoint for the artist, get the artist id, call the albums endpoint with the artist, manually find the album in the result, then call the tracks endpoint, manually find the track, and *then* call the lyrics API.
> 
> 
> 
> Their contact form is broken, so I can't even ask them what I'm missing here.
> 
> 
> 
> Throwaway api key for anyone to play with: `749bc35xp2wI2uOhyuwQ51FbIVwKN2w3Oow64MPIsNNmOnZYIwQXhVwr`

Hi, use search endpoint with lyrics param and call lyrics endpoint in response (only need 2 calls)

**Comment by worsco** [comment]
https://happi.dev/docs/music appears to be down and gone without a trace at this time.  Cloudflare reports the site is down.

**Comment by joaozittoo** [comment]
Happi is **not available** anymore. sad
